# Day 3, part 1

In [1]:
import numpy as np

In [2]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
y = np.arange(10,50)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
z = np.flip(y)
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [8]:
u = np.arange(9).reshape((3,3))
print(u)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
v= np.nonzero([1,2,0,0,4,0])
print(v)

(array([0, 1, 4], dtype=int64),)


In [38]:
w = np.random.rand(30)
mw = np.mean(w)
print(mw)

0.4673071006197534


In [41]:
s = np.ones(9)
s[4] = 0
s = s.reshape(3,3)
print(s)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [30]:
p = np.zeros(64)
p[1:8:2] = 8
p[8:16:2]= 8
p[17:24:2] = 8
p[24:32:2] = 8
p[33:40:2] = 8
p[40:48:2] = 8
p[49:56:2] = 8
p[56:64:2] = 8
p = p.reshape(8,8)
print(p)

[[0. 8. 0. 8. 0. 8. 0. 8.]
 [8. 0. 8. 0. 8. 0. 8. 0.]
 [0. 8. 0. 8. 0. 8. 0. 8.]
 [8. 0. 8. 0. 8. 0. 8. 0.]
 [0. 8. 0. 8. 0. 8. 0. 8.]
 [8. 0. 8. 0. 8. 0. 8. 0.]
 [0. 8. 0. 8. 0. 8. 0. 8.]
 [8. 0. 8. 0. 8. 0. 8. 0.]]


In [43]:
d = np.array([[0,8],[8,0]])
d = np.tile(d, (4,4))
print(d)

[[0 8 0 8 0 8 0 8]
 [8 0 8 0 8 0 8 0]
 [0 8 0 8 0 8 0 8]
 [8 0 8 0 8 0 8 0]
 [0 8 0 8 0 8 0 8]
 [8 0 8 0 8 0 8 0]
 [0 8 0 8 0 8 0 8]
 [8 0 8 0 8 0 8 0]]


In [55]:
f = np.arange(11)
f[4:8] = -f[4:8]
print(f)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [56]:
g = np.random.random(10)
g = np.sort(g)
print(g)

[0.03044267 0.07468194 0.13925191 0.21402803 0.32509009 0.36072165
 0.58222701 0.65965765 0.69080448 0.99075681]


In [59]:
h_1 = np.random.randint(0,2,5)
h_2 = np.random.randint(0,2,5)
equal = h_1 == h_2
print(equal)

[False  True False  True  True]


In [61]:
k = np.arange(10, dtype=np.int32)
print(k.dtype)
k = k.astype(np.float32)
print(k.dtype)

int32
float32


In [64]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.diag(C)
print(D)

[ 18  66 132]


# Day 3, part 2

This is the same as my optimisation in the task for day 2! I saw on slack that using np was recommended so that is what I did. Hope that is ok!

# Day 3, part 3

In [19]:
class Person:
    def __init__(self, firstname, lastname):
        self.firstname = firstname
        self.lastname = lastname
        
    def fullname(self):
        return '{self.lastname}, {self.firstname} {self.lastname}'.format(self=self) 

In [54]:
class Student(Person):
    def __init__(self, firstname, lastname, subject):
        super().__init__(firstname, lastname)
        self.subject = subject
        
    @classmethod
    def whoareyou_stud(cls, stud):
        print('My name is ' + stud.lastname +', ' +stud.firstname +' '+ stud.lastname +', and I study ' +stud.subject+'.')

stud1 = Student('James','Bond','Intersectional feminism 101')
Student.whoareyou(stud1)
# I hope it's ok to have a Student.printNameSubject(me) structure instead of a me.printNameSubject structure

My name is Bond, James Bond, and I study Intersectional feminism 101.


In [65]:
class Teacher(Person):
    def __init__(self, firstname, lastname):
        super().__init__(firstname, lastname)
        
    @classmethod
    def whoareyou_teacher(cls, course):
            print('My name is ' + teacher.lastname +', ' +teacher.firstname +' '+ teacher.lastname +', and I teach ' +course+'.')

course = 'Intersectional feminism 101'
teacher =Teacher('Miss', 'Moneypenny')
Teacher.whoareyou_teacher(course)

My name is Moneypenny, Miss Moneypenny, and I teach Intersectional feminism 101.
